---
# Ansible variables
ansible_user: vagrant
# ansible_user: dt\vagrant
ansible_password: ThisIsASecurePassword!2022

citrix_version_name: Citrix_Virtual_Apps_and_Desktops_7_2305
citrix_controller: ctx-ctrl-01
domain_fqdn: dt.democloud
citrix_url: citrix.democloud.devicetrust.com

# Citrix variables
citrix:

  # Citrix version variables
  version: 
    number: '2305'
    name: Citrix_Virtual_Apps_and_Desktops_7_2305

  # Citrix installation variables
  installation:
   source: Citrix_Virtual_Apps_and_Desktops_7_2305.iso
   zip: Citrix_Virtual_Apps_and_Desktops_7_2305.zip
   path: "http://10.10.99.22:8080/share/sources/citrix/cvda"

  # Citrix admin variables
  admin:
    user: dt\vagrant
    password: ThisIsASecurePassword!2022

  # Citrix site variables
  site: 
    name: democloud
    database:
      server: localhost\ANSIBLE
      port: 1433
      site: CVAD_Site_DB
      logging: CVAD_Logging_DB
      monitoring: CVAD_Monitoring_DB
    admin: 
      group: Domain Admins
      role: Full Administrator
      scope: All
      grooming: 365
    licensing:
      server: localhost
      port: 27000
      model: Concurrent
      code: XDT
      edition: PLT
    ddc: '{{ citrix_controller }}.{{ domain_fqdn }}'
    siteconfig:
      machinecatalog: MC_Test
      deliverygroup: DG_Test
      desktop: Desktop
      vdahostname: ctx-rdsh-01
      usergroup: g_g_sec_citrix_users

  # Citrix storefront variables
  storefront:
    url: 'http://{{ citrix_url }}'
    hostbaseurl: 'http://{{ citrix_url }}'
    farmservers: '{{ citrix_controller }}.{{ domain_fqdn }}'
    path: /Citrix/Store
    transporttype: http
    gateway:
      name: inf-adc-01
      url: 'https://{{ citrix_url }}'
      staurl: 'http://{{ citrix_controller }}'
    installation:
      prereqs: ['Web-Server','Web-WebServer','Web-Common-Http','Web-Default-Doc','Web-Dir-Browsing','Web-Http-Errors','Web-Static-Content','Web-Http-Redirect','Web-Health','Web-Http-Logging','Web-Log-Libraries','Web-Http-Tracing','Web-Performance','Web-Stat-Compression','Web-Dyn-Compression','Web-Security','Web-Filtering','Web-Basic-Auth','Web-Windows-Auth','Web-App-Dev','Web-Net-Ext45','Web-AppInit','Web-ASP','Web-Asp-Net45','Web-CGI','Web-ISAPI-Ext','Web-ISAPI-Filter','Web-Includes','Web-Mgmt-Tools','Web-Mgmt-Console','Web-Mgmt-Compat','Web-Metabase','Web-Lgcy-Mgmt-Console','Web-Lgcy-Scripting','Web-WMI','Web-Scripting-Tools','NET-Framework-Features','NET-Framework-45-Features','NET-Framework-45-Core','NET-Framework-45-ASPNET','NET-WCF-Services45','NET-WCF-HTTP-Activation45','NET-WCF-TCP-PortSharing45','WAS','Telnet-Client']
      path: "http://10.10.99.22:8080/share/sources/citrix/cvda"
      source: 'Citrix_Virtual_Apps_and_Desktops_7_2305.iso'
  
  # Citrix director variables
  director:
    url: director.{{ domain_fqdn }}

  # Citrix ddc variables
  ddc: 
    name: '{{ citrix_controller }}.{{ domain_fqdn }}'
    installation:
     exepath: '\x64\XenDesktop Setup\XenDesktopServerSetup.exe'
     params_full: '/COMPONENTS CONTROLLER,DESKTOPSTUDIO,DESKTOPDIRECTOR,LICENSESERVER /CONFIGURE_FIREWALL /QUIET /NOSQL /ignore_hw_check_failure'
     prereqs: ['NET-Framework-Core','NET-Framework-45-Core','NET-Framework-45-ASPNET','GPMC','RSAT-ADDS-Tools','RDS-Licensing-UI','WAS','Telnet-Client','GPMC','Remote-Assistance','RSAT-AD-Tools','Web-Server','Web-WebServer','Web-Common-Http','Web-Default-Doc','Web-Dir-Browsing','Web-Http-Errors','Web-Static-Content','Web-Http-Redirect','Web-Health','Web-Http-Logging','Web-Log-Libraries','Web-Http-Tracing','Web-Performance','Web-Stat-Compression','Web-Dyn-Compression','Web-Security','Web-Filtering','Web-Basic-Auth','Web-Windows-Auth','Web-Net-Ext45','Web-ASP','Web-ASP-Net45','Web-CGI','Web-ISAPI-Ext','Web-ISAPI-Filter','Web-Includes','Web-WebSockets','Web-Mgmt-Tools','Web-Mgmt-Console','Web-Mgmt-Compat','Web-Metabase','Web-Lgcy-Mgmt-Console','Web-Lgcy-Scripting','Web-WMI','Web-Scripting-Tools']

  # Citrix rdsh variables
  rdsh:
    vda:
      installation:
        zip: VDAServerSetup_2305.zip
        exe: VDAServerSetup_2305.exe
        path: "http://10.10.99.22:8080/share/sources/citrix/cvda"
        exepath: '\Image-Full\x64\XenDesktop Setup\XenDesktopVDASetup.exe'
        prereqs: ['Telnet-Client','RDS-RD-Server','Remote-Assistance']
        params_full: '/passive /controllers {{ citrix_controller }} /enable_hdx_ports /components vda /exclude "Machine Identity Service","Citrix Profile Management","Citrix Profile Management WMI Plug-in","Citrix Personalization for App-V - VDA","Citrix MCS IODriver","Citrix VDA Upgrade Agent","Citrix Rendezvous V2"'    
        software:
    fslogix:
      rulesfolder: 'C:\Program Files\FSLogix\Apps\Rules'
    misc:
      wallpaperfolder: 'c:\files'

citrix_rdsh_fslogix_folder: 'C:\Program Files\FSLogix\Apps\Rules'