---
# tasks file for ansible-role-win-domainjoin

- name: Join Domain
  win_domain_membership:
    dns_domain_name: "{{ domainjoin_domain_name }}"
    domain_admin_user: "{{ domainjoin_user_name}}"
    domain_admin_password: "{{ domainjoin_user_pw }}"
    state: domain
  notify: reboot