---
- name: Copy the Citrix Policy input file
  win_copy:
    src: CitrixPolicy.txt
    dest: '{{ directory_install }}'

- name: Configure Site
  script: config.ps1
  args:
    creates: '{{ directory_logging }}done-config.txt'
  environment:
    citrix_siteconfig_vdahostname: "{{ citrix.site.siteconfig.vdahostname }}"
    citrix_siteconfig_machinecatalog: "{{ citrix.site.siteconfig.machinecatalog }}"
    citrix_siteconfig_deliverygroup: "{{ citrix.site.siteconfig.deliverygroup }}"
    citrix_siteconfig_desktop: "{{ citrix.site.siteconfig.desktop }}"
    citrix_siteconfig_usergroup: "{{ citrix.site.siteconfig.usergroup }}"