---
#####################################
### Create DNS Records
#####################################

- name: Create DNS Records
  community.windows.win_dns_record:
    name: '{{ item.name }}'
    type: '{{ item.type }}'
    value: '{{ item.ip }}'
    zone: '{{ dc_dns_zone_name }}'
  with_items: "{{ dc_dns_records }}"