version: "3.7"

services:
    runner:
      image: devicetrust/github-runner:latest
      environment:
        - ACCESS_TOKEN=${ACCESS_TOKEN}
        - RUNNER_SCOPE=${RUNNER_SCOPE}
        - RUNNER_NAME_PREFIX=${RUNNER_NAME_PREFIX}
        - LABELS=${LABELS}
        - RUNNER_GROUP=${RUNNER_GROUP}
        - REPO_URL=${REPO_URL}
      volumes:
        - ../env_democloud/ansible:/ansible-files
        - ../env_democloud/terraform:/terraform-files
        - ../shared_packer:/packer-files
