---
  - name: Install license file
    win_copy:
      src: "{{ item }}"
      dest: C:\Program Files (x86)\Citrix\Licensing\MyFiles\
    with_fileglob:
      - "*.lic"

  - name: Reboot after License
    win_reboot: