---
#######################################################
### Reset standard user passwords and unlock accounts
#######################################################

- name: Reset standard user passwords and unlock accounts
  community.windows.win_domain_user:
    name: '{{ item }}'
    password: '{{ dc.domain.passwords.service }}'
    domain_password: '{{ dc.domain.passwords.service }}'
    account_locked: false
    password_never_expires: true
    update_password: always
    user_cannot_change_password: true
  with_items: '{{ dc_user_service }}'

#######################################################
### Reset service user passwords and unlock accounts
#######################################################

- name: Reset service user passwords and unlock accounts
  community.windows.win_domain_user:
    name: '{{ item }}'
    password: '{{ dc.domain.passwords.user }}'
    domain_password: '{{ dc.domain.passwords.user }}'
    account_locked: false
    password_never_expires: true
    update_password: always
    user_cannot_change_password: true
  with_items: '{{ dc_user_standard }}' 