---
- name: Enable windows update service
  win_service:
    name: wuauserv
    start_mode: auto
    state: started

- name: Install all Windows updates and reboot as many times as needed
  ansible.windows.win_updates:
    category_names: '*'
    reboot: yes

- name: Disable windows update service
  win_service:
    name: wuauserv
    start_mode: disabled
    state: stopped