---
public_hosting_domain: democloud.devicetrust.com
# docker_container_guac_volume_dir: guac_home

# infra_dh
docker_compose_version: 1.29.2
docker_users: localadmin
docker_daemon_options:
  bip: '172.29.0.1/16'
  default-address-pools:
    - { base: '172.73.0.0/16', size: 24 }

# Docker
docker_host_subnet_base: 172.73.0.0/16
docker_host_subnet_size: 24
docker_host_bridge_ip: 172.29.0.1/16
docker_container_volume_base_dir: /srv/docker_data
docker_container_guac_volume_dir: '{{ docker_container_volume_base_dir }}/{{ docker_container_guac_name }}'
docker_container_guac_db_volume_dir: '{{ docker_container_volume_base_dir }}/{{ docker_container_guac_db_name }}'
docker_container_guac_extensions_volume_dir: '{{ docker_container_guac_volume_dir }}/guac_home/extensions'

# Docker container guac
docker_container_guac_version: 1.4.0
docker_container_guac_name: guac
docker_container_guac_image: guacamole/guacamole

# Docker container guacd
docker_container_guac_d_name: guacd
docker_container_guac_d_image: guacamole/guacd

# Docker container guac-db / mysql
docker_container_guac_db_name: guac-db
docker_container_guac_db_image: mysql

# Guacamole 
guac_mfa_enabled: true
guac_ldap_enabled: true

guac_db_name: guacamole
guac_db_user: guacadmin
guac_db_password: S00perSecurePassw0rd2023
guac_db_root_password: S00perSecurePassw0rd2023

guac_ldap_admin_user: svc_ldap
guac_ldap_admin_group: g_g_sec_guac_admins
guac_root_connection_group_prefix: presales
guac_root_connection_groups: [presales01,presales02]

ansible_hostname: controller

linux_software_apt: ['docker','docker-compose']

domain_admin_password: S00perSecurePassw0rd2023

guac_connection_sql_file_prefix: '{{ guac_root_connection_group }}'
guac_connection_names: ['rdsh','client','byod']

dns_domain_name: dt.presales
win_user_language: en-us

docker_container_names: ['{{ docker_container_guac_name }}','{{ docker_container_guac_d_name }}','{{ docker_container_guac_db_name }}']

LDAP_HOSTNAME: 10.10.2.10
LDAP_PORT: '389'
LDAP_ENCRYPTION_METHOD: none
LDAP_USER_BASE_DN: 'OU=Objects,DC=dt,DC=presales'
LDAP_GROUP_BASE_DN: 'DC=dt,DC=presales'
LDAP_SEARCH_BIND_DN: svc_ldap@dt.presales
LDAP_SEARCH_BIND_PASSWORD: S00perSecurePassw0rd2023
LDAP_USERNAME_ATTRIBUTE: sAMAccountName
LDAP_GROUP_NAME_ATTRIBUTE: cn
LDAP_MEMBER_ATTRIBUTE: member
LDAP_USER_SEARCH_FILTER: '(objectClass=user)(!(objectCategory=computer))'