---
- name: Install prerequisites
  become: true
  ansible.builtin.apt:  
    name: '{{ item }}'
    state: present
  with_items: '{{ linux.logging.prerequisites }}'

- name: Remove old data
  become: true
  file:
    path: '{{ linux.logging.gitfolder }}'
    state: absent

- name: Create GIT folder
  become: true
  file:
    path: '{{ linux.logging.gitfolder }}'
    state: directory

- name: Clone github repository
  become: true
  shell: |
    cd '{{ linux.logging.gitfolder }}'
    git clone '{{ linux.logging.githubrepository }}'

- name: Stop Docker container
  become: true
  shell: |
    cd '{{ linux.logging.gitfolder }}/democloud-docker-logging'
    docker-compose rm --stop --force

- name: Create Docker container
  become: true
  shell: |
    cd '{{ linux.logging.gitfolder }}/democloud-docker-logging'
    docker-compose up -d