- hosts: computers
  gather_facts: no

  tasks:
  - name: Remove printer iR-ADV C7260
    win_shell: |
      $printers = Get-Printer | Where-Object {$_.Name -like "*C7260*"}
      ForEach ($printer in $printers) {
          Remove-Printer -Name $printer.Name
      }
      $printerdriver = Get-PrinterDriver | Where-Object {$_.Name -like "*iR-ADV*"}
      ForEach ($printerdriver in $printerdrivers) {
          Remove-PrinterDriver -Name $printerdriver.Name
      }
      $printerport = Get-PrinterPort | Where-Object {$_.Name -like "*192.168.0.40*"}
      ForEach ($printerport in $printerports) {
          Remove-PrinterPort -Name $printerrt.Name
      }
      If ($printers -or $printerdrivers -or $printerports) {
          Write-Host "changed"
      }
    register: canon_c7260
    failed_when: no
    changed_when: canon_c7260.stdout.find("changed") != -1

  - name: Remove printer driver
    win_shell: |
      $drivers = (Get-WindowsDriver -online  | Where-Object {$_.OriginalFileName -like "*cnp60ha64.inf"}).Driver
      ForEach ($driver in $drivers) {
          PNPUtil.exe /delete-driver $driver
      }
    register: removal
    failed_when: no
    changed_when: removal.stdout.find("Driver package deleted successfully.") != -1

  - name: Install printer driver
    win_shell: |
      Set-Location -LiteralPath "\\diskstation01.crombeen.internal\ictadmin\Hardware\Printer\Canon iR ADVANCE\GPlus_PCL6_Driver_V200_32_64_00\x64\Driver"
      PNPUtil.exe /add-driver CNP60MA64.INF /install
    register: driver
    changed_when: 'driver.stdout.find("Added driver packages:  1") != -1'
    failed_when: driver.stdout.find("Driver package added successfully.") == -1

  - name: Create printer iR-ADV 6555
    win_shell: |
      Add-PrinterPort -Name "IP_192.168.0.225" -PrinterHostAddress "canon_6555.crombeen.internal" -PortNumber 9100
      Add-PrinterDriver -Name "Canon Generic Plus PCL6"
      Add-Printer -Name "iR-ADV 6555 III (Zwart-Wit Crombeen)" -DriverName "Canon Generic Plus PCL6" -Port "IP_192.168.0.225"
    register: canon_6555
    failed_when: no
    changed_when: canon_6555.rc == 0

  - name: Set default printer
    win_shell: |
      $wshNet = New-Object -ComObject WScript.Network
      $wshNet.SetDefaultPrinter("iR-ADV 6555 III (Zwart-Wit Crombeen)")
    tags: default

  - name: Do not let Windows manage your default printer
    win_regedit:
      path: HKCU:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows
      name: LegacyDefaultPrinterMode
      data: 1
      type: dword
    tags: registry