---
  - name: Prepare machine for auto-logon to support DDC installation - 1
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: AutoAdminLogon
      data: 1
      state: present

  - name: Prepare machine for auto-logon to support DDC installation - 2
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: DefaultUserName
      data: '{{ ansible_user }}'
      state: present

  - name: Prepare machine for auto-logon to support DDC installation - 3
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: DefaultPassword
      data: '{{ ansible_password }}'
      state: present

  - name: Create Install Folder
    win_file:
      path: '{{ directory_install }}'
      state: directory

  - name: Create Citrix Install Folder
    win_file:
      path: '{{ directory_install }}\Citrix'
      state: directory

  - name: Download Citrix ZIPfile
    win_get_url:
      url: '{{citrix.installation.path}}/{{citrix.version.number}}/{{citrix.installation.zip}}'
      dest: '{{ directory_install }}\Citrix\{{citrix.installation.zip}}'

  - name: Unzip ZIP
    community.windows.win_unzip:
      src: '{{ directory_install }}\Citrix\{{citrix.installation.zip}}'
      dest: '{{ directory_install }}\Citrix'

  - name: Install DDC Components
    win_package:
      path: '{{ directory_install }}\Citrix\{{ citrix.version.name }}\{{ citrix.ddc.installation.exepath }}'
      arguments: '{{ citrix.ddc.installation.params_full }}'
      state: present
      expected_return_code: [0, 3, 3010]
      creates_path: 'C:\Program Files\Citrix\Desktop Studio'
    become: true
    become_method: runas
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    vars:
      ansible_become_user: '{{ ansible_user }}'
      ansible_become_pass: '{{ ansible_password }}'
    register: ddc_install_started

  - name: Pause for 10 minutes
    ansible.builtin.pause:
      minutes: 10

  - name: Wait for Windows Installer process to stop
    community.windows.win_wait_for_process:
      process_name_exact: 'msiexec'
      state: absent
      timeout: 900

  - name: Remove auto-logon reg keys - 1
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: AutoAdminLogon
      state: absent

  - name: Remove auto-logon reg keys - 2
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: DefaultUserName
      state: absent

  - name: Remove auto-logon reg keys - 3
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: DefaultPassword
      state: absent

  - name: Reboot
    ansible.windows.win_reboot: