---
# tasks file for ansible-role-win-domain
- name: Windows Feature AD-Domain-Services and Tools
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- name: reboot if installing AD-Domain-Services feature requires it
  win_reboot:
  when: win_feature.reboot_required