---
# Ansible variables
ansible_connection: ssh
ansible_shell_type: 'powershell'
ansible_pipelining: true
ansible_path_temp: c:\AnsibleTemp

# Domain configuration variables
win:
  domain:
    tld: democloud
    netbios: dt
    dnsname: 'dt.democloud'
  user:
    language: de-DE
  software:
    chocolatey: ['7zip','firefox','Notepadplusplus','Adobereader','FSLogix']
  smbhare:
    path: '\\10.10.99.22' # ToDo
    username: 'share'
    password: 'deviceTRUST$'
    letter: 'S'
  directory:
    logging: 'c:\logs'
    install: 'c:\install'
    gpo: 'c:\gpo'

win_domain_tld: democloud
win_domain_netbios: dt
win_domain_dnsname: 'dt.democloud'
win_user_language: de-DE
win_software_chocolatey: ['7zip','firefox','Notepadplusplus','Adobereader','FSLogix']
win_smbhare_path: '\\10.10.99.22' # ToDo
win_smbhare_username: 'share'
win_smbhare_password: 'deviceTRUST$'
win_smbhare_letter: 'S'
win_directory_logging: 'c:\logs'
win_directory_install: 'c:\install'
win_directory_gpo: 'c:\gpo'

# Alternative SMB Share information for software sources
smb_share:
  - path: '\\10.10.99.22' # ToDo
  - username: 'share'
  - password: 'deviceTRUST$'

smb_share_path: 10.10.99.22 # ToDo
smb_share_username: 'share'
smb_share_password: 'deviceTRUST$'
smb_share_letter: 'S'

directory_logging: 'c:\logs'
directory_install: 'c:\install'
directory_gpo: 'c:\gpo'

win_software_chocolatey_citrix: ['dt-agent','dt-console','fslogix']